import { heroPortrait, portraitForId } from "./character-portraits";
import type {
  ExploreAgeRange,
  ExploreCharacter,
  ExploreFilterTag,
  ExploreGender,
  ExploreStyle,
} from "./explore-characters";

export type {
  ExploreAgeRange,
  ExploreCharacter,
  ExploreFilterTag,
  ExploreGender,
  ExploreStyle,
};

export { EXPLORE_FILTER_TAGS, matchesAgeRange } from "./explore-characters";

const HOME_CHARACTERS_BASE: ExploreCharacter[] = [
  {
    id: "home-mia",
    name: "Mia",
    age: 22,
    bio: "Sunset walks and voice notes — she answers every call with a warm laugh.",
    tags: ["Blonde", "Romantic", "Busty"],
    filterTags: ["Blonde", "Romantic", "Teen"],
    image: portraitForId("home-mia"),
    gender: "female",
    style: "realistic",
    isNew: true,
    createdAt: "2026-06-04",
  },
  {
    id: "home-sophie",
    name: "Sophie",
    age: 19,
    bio: "Shy art student who opens up over late-night chats and shared playlists.",
    tags: ["Teen", "Shy", "Creative"],
    filterTags: ["Teen", "Shy"],
    image: portraitForId("home-sophie"),
    gender: "female",
    style: "realistic",
    createdAt: "2026-06-02",
  },
  {
    id: "home-valentina",
    name: "Valentina",
    age: 24,
    bio: "Bold latina dancer — confident energy, sharp wit, loyal to the end.",
    tags: ["Latina", "Busty", "Fitness"],
    filterTags: ["Latina", "Busty", "Fitness"],
    image: portraitForId("home-valentina"),
    gender: "female",
    style: "realistic",
    createdAt: "2026-05-30",
  },
  {
    id: "home-harper",
    name: "Harper",
    age: 20,
    bio: "E-girl gamer who memes by day and sends cozy voice messages at night.",
    tags: ["Gamer", "Shy", "E-Girl"],
    filterTags: ["Gamer", "Shy", "Teen"],
    image: portraitForId("home-harper"),
    gender: "female",
    style: "anime",
    createdAt: "2026-05-28",
  },
  {
    id: "home-elena",
    name: "Elena",
    age: 35,
    bio: "Sophisticated MILF energy — wine nights, deep talks, and zero judgment.",
    tags: ["MILF", "Romantic", "Caring"],
    filterTags: ["MILF", "Romantic", "Caring"],
    image: portraitForId("home-elena"),
    gender: "female",
    style: "realistic",
    createdAt: "2026-05-26",
  },
  {
    id: "home-zoe",
    name: "Zoe",
    age: 21,
    bio: "Beach volleyball spirit — spontaneous, flirty, and always up for adventure.",
    tags: ["Blonde", "Fitness", "Adventurous"],
    filterTags: ["Blonde", "Fitness", "Teen"],
    image: portraitForId("home-zoe"),
    gender: "female",
    style: "realistic",
    createdAt: "2026-05-24",
  },
  {
    id: "home-aria",
    name: "Aria",
    age: 28,
    bio: "Dominant executive who balances power suits with whispered secrets.",
    tags: ["Dominant", "MILF", "Bold"],
    filterTags: ["Dominant", "MILF"],
    image: portraitForId("home-aria"),
    gender: "female",
    style: "realistic",
    adultOnly: true,
    createdAt: "2026-05-22",
  },
  {
    id: "home-priya",
    name: "Priya",
    age: 23,
    bio: "Thoughtful and cultured — tea, museums, and conversations that go deep.",
    tags: ["Asian", "Caring", "Romantic"],
    filterTags: ["Asian", "Caring", "Romantic"],
    image: portraitForId("home-priya"),
    gender: "female",
    style: "realistic",
    createdAt: "2026-05-20",
  },
  {
    id: "home-jade",
    name: "Jade",
    age: 27,
    bio: "Chef and flirt — she'll plan dinner dates and tease you until you blush.",
    tags: ["Busty", "Romantic", "Latina"],
    filterTags: ["Busty", "Romantic", "Latina"],
    image: portraitForId("home-jade"),
    gender: "female",
    style: "realistic",
    createdAt: "2026-05-18",
  },
  {
    id: "home-naomi",
    name: "Naomi",
    age: 22,
    bio: "Surfer energy — laid-back, loyal, and always planning the next road trip.",
    tags: ["Ebony", "Adventurous", "Fitness"],
    filterTags: ["Ebony", "Fitness"],
    image: portraitForId("home-naomi"),
    gender: "female",
    style: "realistic",
    createdAt: "2026-05-16",
  },
  {
    id: "home-lilith",
    name: "Lilith",
    age: 23,
    bio: "Goth stargazer — astronomy facts mixed with soft, intimate chat.",
    tags: ["Goth", "Shy", "Romantic"],
    filterTags: ["Goth", "Shy", "Romantic"],
    image: portraitForId("home-lilith"),
    gender: "female",
    style: "anime",
    createdAt: "2026-05-14",
  },
  {
    id: "home-camille",
    name: "Camille",
    age: 30,
    bio: "Calm wellness coach who blends mindfulness with playful banter.",
    tags: ["MILF", "Caring", "Fitness"],
    filterTags: ["MILF", "Fitness", "Caring"],
    image: portraitForId("home-camille"),
    gender: "female",
    style: "realistic",
    createdAt: "2026-05-12",
  },
  {
    id: "home-ivy",
    name: "Ivy",
    age: 20,
    bio: "Cosplay creator with stage presence and a heart of gold backstage.",
    tags: ["Cosplay", "Asian", "Bold"],
    filterTags: ["Cosplay", "Asian", "Teen"],
    image: portraitForId("home-ivy"),
    gender: "female",
    style: "anime",
    createdAt: "2026-05-10",
  },
  {
    id: "home-grace",
    name: "Grace",
    age: 44,
    bio: "Warm and understanding — the kind of presence that makes you feel seen.",
    tags: ["MILF", "Loving", "Caring"],
    filterTags: ["MILF", "Caring"],
    image: portraitForId("home-grace"),
    gender: "female",
    style: "realistic",
    createdAt: "2026-05-08",
  },
  {
    id: "home-sienna",
    name: "Sienna",
    age: 21,
    bio: "Party girl with gyaru flair — neon nights, loud laughs, real connection.",
    tags: ["Asian", "Adventurous", "Bold"],
    filterTags: ["Asian", "Teen"],
    image: portraitForId("home-sienna"),
    gender: "female",
    style: "realistic",
    adultOnly: true,
    createdAt: "2026-05-06",
  },
  {
    id: "home-nova",
    name: "Nova",
    age: 24,
    bio: "Your signature companion — empathetic, witty, remembers what matters.",
    tags: ["Caring", "Supportive", "Romantic"],
    filterTags: ["Caring", "Romantic"],
    image: portraitForId("home-nova"),
    gender: "female",
    style: "realistic",
    isNew: true,
    createdAt: "2026-06-03",
  },
  {
    id: "home-reese",
    name: "Reese",
    age: 24,
    bio: "Authentic and affirming — celebrates you as you are, no filters.",
    tags: ["Caring", "Romantic", "Creative"],
    filterTags: ["Caring", "Romantic"],
    image: portraitForId("home-reese"),
    gender: "trans",
    style: "realistic",
    isNew: true,
    createdAt: "2026-06-01",
  },
];

export const HOME_CHARACTERS: ExploreCharacter[] = HOME_CHARACTERS_BASE;

export const HOME_HERO_IMAGE = heroPortrait("home", 1600, 420);

export const HOME_JOIN_AVATARS = [
  portraitForId("home-join-1", 80, 80),
  portraitForId("home-join-2", 80, 80),
  portraitForId("home-join-3", 80, 80),
  portraitForId("home-join-4", 80, 80),
] as const;
